<?php
namespace Chatbox\PostalCode;
/**
 * Created by PhpStorm.
 * User: mkkn
 * Date: 2015/04/19
 * Time: 18:45
 */

use Chatbox\Rumic\Application as Rumic;

class Application extends Rumic{

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->loadEnv(__DIR__."/../../");
        $this->setConfigPath(__DIR__."/../config/");
        $this->setStoragePath(__DIR__."/../../");
//        $this->setResourcePath(PROJECTROOT."/app/resource/");
        $this->withEloquent();

        $this->configurateImplements([
            ['Illuminate\Contracts\Debug\ExceptionHandler','Chatbox\Rumic\Exceptions\Handler',true],
            ['Illuminate\Contracts\Console\Kernel',        'Chatbox\PostalCode\Console\Kernel',    true],
        ]);
        $this->configurateProviders([
//            new \Website\Providers\ViewComposerServiceProvider($this),
            new \Chatbox\PostalCode\Providers\AppRouteServiceProvider($this),
        ]);

//        $this["view"]->composer("hoge",function($view){
//            $view->with("message","hogepiyo");
//        });
    }


}